"""Recover executed source evidence; never instantiate a guessed physical magnet."""
from pathlib import Path
import hashlib,json,importlib.util,ast
import numpy as np,ezdxf
ROOT=Path('H:/fluent'); BASE=Path('J:/abaqusfangzhen/abaqus_robot/calibration_analysis'); CASE=BASE/'TrueCELLongForwardTransit/case/TRUECEL_B0P11_G2P20_F100_NOFLUID_CONTROL'; OUT=ROOT/'magnetic/L2300_Abaqus100Hz_v1';OUT.mkdir(parents=True,exist_ok=True)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
identity=json.loads((CASE/'case_identity.json').read_text())
sta=list(CASE.glob('*.sta'));assert any('THE ANALYSIS HAS COMPLETED SUCCESSFULLY' in p.read_text(errors='replace') for p in sta)
server=Path('J:/magpy/magpylib_socket_server.py');s=importlib.util.spec_from_file_location('old',server);m=importlib.util.module_from_spec(s);s.loader.exec_module(m)
a=m.MagneticCouplingModel.__new__(m.MagneticCouplingModel);curve=a._read_dxf_curve(ezdxf,'J:/magpy/curvenew_CEL_xyrot56_exact.dxf');tangent=curve[1]-curve[0];tangent/=np.linalg.norm(tangent)
R=np.array(json.load(open('J:/abaqusfangzhen/abaqus_magpylib_frame_transform.json'))['R_aba_to_mag']); moment_axis_aba=-R.T@tangent
axis=np.array([.9647382600216,-.1188742372140,.2348382536499]);axis/=np.linalg.norm(axis);v=np.cross([1,0,0],axis);K=np.array([[0,-v[2],v[1]],[v[2],0,-v[0]],[-v[1],v[0],0]]);Q=np.eye(3)+K+K@K/(1+axis[0]);moment_body=Q.T@moment_axis_aba*.0010400401426980412
paths=[CASE/'vuamp_precomputed_truecel.f90',CASE/'magnetic_field_gradient_table_B0P11_A14P5.dat',CASE/'case_identity.json',*sta,BASE/'TrueCELLongForwardTransit/scripts/prepare_f100_nofluid_control.py',BASE/'PrecomputedStraightMagneticBackend/scripts/table_model.py',BASE/'ReducedHydro_L2300_frozenCAD_validation/same_pose_magnetic_regression.py',BASE/'ReducedHydro_L2300_frozenCAD_validation/build_l2300_deck.py',BASE/'ReducedHydro_L2300_frozenCAD_validation/audit_frozen_cad_static.py',server,Path('J:/abaqusfangzhen/abaqus_magpylib_frame_transform.json'),Path('J:/magpy/curvenew_CEL_xyrot56_exact.dxf'),BASE/'MagneticTrapAudit/PHYSICAL_MAGNET_SOURCE_MANIFEST.json']
paths += [BASE/'ReducedHydro_L2300_frozenCAD_validation/run_l2300.ps1',BASE/'PrecomputedStraightMagneticBackend/scripts/precompute_straight_magnetic_table.py',BASE/'FastStraightDynamicScreen/production/magpylib_socket_server_fast.py',CASE/'magnetic_field_gradient_table_B0P11_A14P5.dat.json']
files=[dict(path=str(p),sha256=sha(p),modified_ns=p.stat().st_mtime_ns) for p in paths]
# Inventory all requested historical project extensions, then preserve the executed dependency chain.
roots=[Path('J:/abaqusfangzhen'),ROOT/'magnetic',ROOT/'scripts',ROOT/'fluent_udf'];ext={'.py','.java','.inp','.json','.yaml','.csv','.npz','.md'}
counts={str(r):sum(1 for p in r.rglob('*') if p.is_file() and p.suffix.lower() in ext) for r in roots}
report=dict(status='RECOVERED_ANALYTIC_SOURCE',physical_source_status='PHYSICAL_MAGPYLIB_SOURCE_NOT_UNIQUELY_RECOVERABLE',case_name=identity['case_id'],successful_dynamics_evidence=[str(p) for p in sta],source_files=files,search_inventory=counts,external_source_type='prescribed analytic B and independently prescribed gradient',physical_geometry=None,physical_magnetization=None,physical_source_center=None,physical_rotation_axis=None,authoritative_frequency_hz=100,legacy_frequency_hz=120,resolution='source-code precedence',B0_T=.011,gradient_amplitude_T=.0022,gradient_length_m=.045,phase_zero_rad=0,drive_sense=1,rocking_main_deg=14.5,rocking_cross_deg=2.5,ramp_duration_s=.001,ramp_law='q*q*(3-2*q), q=t/0.001 during startup; 1 thereafter',driver_speed_m_s=.006,initial_relative_axial_offset_m=.031699921242759284,source_trajectory_law='s_eff=0.031699921242759284 + (COM-COM0).dot(source_axis) - 0.006*t',source_frame_aba=np.column_stack([identity['canonical_plus_s_axis_aba'],identity['n_routeA_aba'],identity['b_routeA_aba']]).tolist(),magnetic_sphere_example_used=False,robot='Robot_L2300_D0815_WallWobble',magnetic_moment_body_Am2=moment_body.tolist(),moment_direction_evidence='Executed L2300 regression: polarity=-1, DXF first tangent; inverse Abaqus CAD +X rotation. No assumption of longitudinal alignment.',moment_axis_aba=moment_axis_aba.tolist(),lookup_reference='CURRENT COM',torque_reference='CURRENT COM',old_load_model='point-dipole force and intrinsic torque at old RP; old robot identity retained only for cross-check',missing_physical_parameters=['shape/count/dimensions','magnetization/polarization','source centers and initial orientations','physical rotation centers/axes and mechanical trajectory'],benchmark_C_ready=False)
report.update(field_sign_resolution='Use actual production analytic implementation, not table_model.field_unit; helper frame/sign mismatches executed table.',robot_mass_kg=8.904428864007322e-6,robot_COM_m=[.0012060186937156343,0,0],robot_inertia_diagonal_kg_m2=[7.257810693523445e-13,3.929384741151496e-12,3.9293847411514897e-12],physical_Magpylib_source_created=False,old_robot_moment_body_Am2=[-.0010876227522174417,0,0])
for p in [OUT/'external_source_provenance.json',ROOT/'evidence/abaqus_100Hz_magnetic_source_provenance.json']:p.write_text(json.dumps(report,indent=2))
print(json.dumps({'case':identity['case_id'],'moment_body':moment_body.tolist(),'status':report['physical_source_status'],'search_inventory':counts}))
